set schema fn71128;

SELECT * FROM CLIENTS;
SELECT * FROM BOOKED;
DELETE FROM Refuceds;
DELETE FROM BOOKED;
DELETE FROM Waitings;


INSERT INTO BOOKED VALUES (1,19);
INSERT INTO BOOKED VALUES (1,20);
INSERT INTO BOOKED VALUES(1,21);
INSERT INTO BOOKED VALUES (1,1);
INSERT INTO BOOKED VALUES (1,2);
INSERT INTO BOOKED VALUES(1,5);
INSERT INTO BOOKED VALUES(1,8);

SELECT * FROM BOOKED;
SELECT * FROM Waitings;